# Generated by Django 3.0.6 on 2020-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamine', '0002_auto_20200601_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(),
        ),
    ]
