# Generated by Django 3.0.6 on 2020-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamine', '0008_auto_20200605_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='image/male.png', upload_to='image/'),
        ),
    ]
